// Shared city metadata for scraping scripts. [countryCode, citySlug, cityName, region, countryName]
export const cities = [
  ["us", "new-york", "New York", "NY", "United States"],
  ["us", "los-angeles", "Los Angeles", "CA", "United States"],
  ["us", "chicago", "Chicago", "IL", "United States"],
  ["us", "miami", "Miami", "FL", "United States"],
  ["us", "san-francisco", "San Francisco", "CA", "United States"],
  ["us", "las-vegas", "Las Vegas", "NV", "United States"],
  ["uk", "london", "London", "England", "United Kingdom"],
  ["uk", "manchester", "Manchester", "England", "United Kingdom"],
  ["uk", "birmingham", "Birmingham", "England", "United Kingdom"],
  ["uk", "edinburgh", "Edinburgh", "Scotland", "United Kingdom"],
  ["uk", "glasgow", "Glasgow", "Scotland", "United Kingdom"],
  ["uk", "bristol", "Bristol", "England", "United Kingdom"],
  ["au", "melbourne", "Melbourne", "VIC", "Australia"],
  ["au", "sydney", "Sydney", "NSW", "Australia"],
  ["au", "brisbane", "Brisbane", "QLD", "Australia"],
  ["au", "perth", "Perth", "WA", "Australia"],
  ["au", "adelaide", "Adelaide", "SA", "Australia"],
  ["de", "berlin", "Berlin", "Berlin", "Germany"],
  ["de", "munich", "Munich", "Bavaria", "Germany"],
  ["de", "hamburg", "Hamburg", "Hamburg", "Germany"],
  ["de", "frankfurt", "Frankfurt", "Hesse", "Germany"],
  ["de", "cologne", "Cologne", "North Rhine-Westphalia", "Germany"],
  // Expansion wave 2 (2026-08 market research): CA, NZ, IE, AE.
  ["ca", "toronto", "Toronto", "ON", "Canada"],
  ["ca", "vancouver", "Vancouver", "BC", "Canada"],
  ["ca", "montreal", "Montreal", "QC", "Canada"],
  ["ca", "calgary", "Calgary", "AB", "Canada"],
  ["ca", "ottawa", "Ottawa", "ON", "Canada"],
  ["nz", "auckland", "Auckland", "Auckland", "New Zealand"],
  ["nz", "wellington", "Wellington", "Wellington", "New Zealand"],
  ["nz", "christchurch", "Christchurch", "Canterbury", "New Zealand"],
  ["nz", "queenstown", "Queenstown", "Otago", "New Zealand"],
  ["ie", "dublin", "Dublin", "Leinster", "Ireland"],
  ["ie", "cork", "Cork", "Munster", "Ireland"],
  ["ie", "galway", "Galway", "Connacht", "Ireland"],
  ["ie", "limerick", "Limerick", "Munster", "Ireland"],
  ["ae", "dubai", "Dubai", "Dubai", "United Arab Emirates"],
  ["ae", "abu-dhabi", "Abu Dhabi", "Abu Dhabi", "United Arab Emirates"],
  ["ae", "sharjah", "Sharjah", "Sharjah", "United Arab Emirates"],
];

export const currencyFor = { us: "USD", uk: "GBP", au: "AUD", de: "EUR", ca: "CAD", nz: "NZD", ie: "EUR", ae: "AED" };
